restart_interface:
  name: Restart interface
  description: "Restart the specified network interface by name (tries ifdown/ifup, wifi down/up, network.reload as fallbacks)"
  fields:
    interface:
      description: "Interface name to restart"
      example: "lan"

reboot_router:
  name: Reboot router
  description: "Reboot the target OpenWrt router (prefers ubus system.reboot, falls back to /sbin/reboot)"
  fields: {}
